(WIP) improve first page + fix bugs
BearStudio/react-native-ficus-ui pull request #21
Opened 2024-02-06 16:25 UTC by houssembaltii

2024-02-14 14:18 UTC, charlelisefouasse requested changes

2024-02-14 14:18 UTC, charlelisefouasse commented on docs/src/components/HomepageFeatures/features.js
> +          />
yoann avait fait le retour d'avoir les couleurs en code au lieu d'une image ( car c'est juste des cube de couleur) une raison pour lauqelle on a laissé une image ?

2024-02-14 14:18 UTC, charlelisefouasse commented on docs/src/components/HomepageFeatures/index.js
>        <>
je referais pas le commentaire a chaque fois du coup je le refais juste la : est-ce qu'on a besoin des fragment ?

2024-02-14 14:18 UTC, charlelisefouasse commented on docs/src/components/HomepageFeatures/index.js
> +const ob=  {
revoir le nom de variable on comprend pas ce que c'est

2024-02-14 14:18 UTC, charlelisefouasse commented on docs/src/components/HomepageFeatures/index.js
>            {FeatureList.map((props, idx) => (
```suggestion
          {FeatureList.map((feature, idx) => (
```

2024-02-14 14:18 UTC, charlelisefouasse commented on docs/src/components/HomepageFeatures/features.js
> +        {Theme.map((Theme, index) => (
```suggestion
        {Theme.map((theme, index) => (
```

2024-02-14 14:18 UTC, charlelisefouasse commented on docs/src/components/HomepageFeatures/features.js
> +const ThemesTable = () => {
```suggestion
const themesTable = () => {
```

2024-02-14 14:18 UTC, charlelisefouasse commented on docs/src/components/HomepageFeatures/features.js
> +  const Theme = [
```suggestion
  const theme = [
```

2024-02-14 14:18 UTC, charlelisefouasse commented on docs/src/components/HomepageFeatures/detailledFeatures.js
> +          {FeatureList.map((props, idx) => (
```suggestion
          {FeatureList.map((feature, idx) => (
```

2024-02-14 14:18 UTC, charlelisefouasse commented on docs/src/components/HomepageFeatures/index.js
> +        <feature.icon size={30} strokeWidth={1} 	 />
```suggestion
        <feature.icon size={30} strokeWidth={1} />
```
Tu n'as pas l'extension prettier qui formatte ton code ?

2024-02-14 14:18 UTC, charlelisefouasse commented on docs/src/components/HomepageFeatures/index.js
> +        <div className="row ">
```suggestion
        <div className="row">
```

idem la il te faut prettier

2024-02-14 14:18 UTC, charlelisefouasse commented on docs/src/pages/index.js
> +        <p style={{fontWeight:'bold'}}>Currently v1.0.0-beta7</p>
si on affiche la verison a plusieurs endroit ca sera interessant de l'etraire en constante générale pour tout le site comme ca on change qu'a un endroit

2024-02-14 14:18 UTC, charlelisefouasse commented on docs/src/components/HomepageFeatures/styles.module.css
> +  }
on peut pas regrouper ensemble TryItLiveDescription ?

2024-02-14 14:18 UTC, charlelisefouasse commented on docs/src/theme/Footer/LinkItem/index.js
> +import * as Icons from 'react-icons/fa'
on peut pas faire mieux qu'importer TOUTES les icones ?

2024-02-15 16:06 UTC, houssembaltii commented on docs/src/components/HomepageFeatures/features.js
> +const ThemesTable = () => {
Cela n'est pas valide car 'themestable' est une fonction qui retourne la table des tailles, et je l'appelle dans ce bout de code.

![image](https://github.com/BearStudio/react-native-ficus-ui/assets/155462028/d654b552-cb6b-4b2e-b71b-720e5589d808)

2024-02-15 16:09 UTC, houssembaltii commented on docs/src/theme/Footer/LinkItem/index.js
> +import * as Icons from 'react-icons/fa'
Je n'ai pas trouvé de solution pour effectuer un import dynamique de ces icônes, donc j'ai essayé une autre approche. Merci de vérifier cela. Si vous avez une autre idée pour ce cas, je suis ouvert à la discussion.

2024-03-19 14:29 UTC, charlelisefouasse commented on docs/src/theme/Footer/LinkItem/index.js
> +import * as Icons from 'react-icons/fa'
Il faut que la props icon soit un react Element donc en gros tu passes directement l'icone (<IconXXX/>) en props comme ca c'est quand tu utilise "FooterLinkItem" que tu importes l'icone

2024-03-21 07:19 UTC, merged